"""Database module."""

from app.db.session import SessionLocal, engine, get_db
from app.db.models import (
    Base,
    RawFile,
    Document,
    Claim,
    IngestRun,
    Patent,
    PatentNumberSource,
    PatentVersion,
    PatentClaim,
    PatentSpecSection,
    IngestionJob,
    IngestionJobItem,
    JpIngestBatch,
    JpIngestBatchFile,
    JpAuditLog,
    JpCase,
    JpDocument,
    JpNumberAlias,
    JpApplicant,
    JpCaseApplicant,
    JpClassification,
    JpStatusEvent,
    JpStatusSnapshot,
    JpSearchDocument,
)

__all__ = [
    "SessionLocal",
    "engine",
    "get_db",
    "Base",
    "RawFile",
    "Document",
    "Claim",
    "IngestRun",
    "Patent",
    "PatentNumberSource",
    "PatentVersion",
    "PatentClaim",
    "PatentSpecSection",
    "IngestionJob",
    "IngestionJobItem",
    "JpIngestBatch",
    "JpIngestBatchFile",
    "JpAuditLog",
    "JpCase",
    "JpDocument",
    "JpNumberAlias",
    "JpApplicant",
    "JpCaseApplicant",
    "JpClassification",
    "JpStatusEvent",
    "JpStatusSnapshot",
    "JpSearchDocument",
]
